version: "3"

# Pentest workstation with Kali
services:
    kali_master:
        build: ./kali
        image: kali
        hostname: kali_master
        container_name: kali_master
        networks:
            net-main_network:
                ipv4_address: 10.10.0.5
        volumes:
            - ./kali/tmp_script:/root/scripts
        command: bash -c "
                    service ssh start &&
                    tail -f /dev/null"
                    
# Network configuration
networks:
    net-main_network:
        ipam:
            config:
                - subnet: 10.10.0.0/16